from typing import List, Optional
from pydantic import BaseModel, Field

class ProductMetadata(BaseModel):
    """
    Pydantic schema representing the extracted metadata from a product image.
    This structure is populated by the VLM and saved to MongoDB.
    """
    sku: Optional[str] = Field(default=None, description="Unique product SKU")
    product_type: str = Field(..., description="E.g., Sneaker, Cotton Kurta, Denim Jacket")
    brand: str = Field(..., description="Brand name")
    price: float = Field(..., description="Retail price")
    primary_color: str = Field(..., description="Dominant color of the product")
    pattern: Optional[str] = Field(default="Solid", description="E.g., Solid, Embroidered, Striped")
    fit: Optional[str] = Field(default="Regular", description="E.g., Regular, Slim, Oversized, Comfort")
    occasions: List[str] = Field(default_factory=list, description="E.g., ['casual wear', 'gym', 'work/office']")
    image_paths: List[str] = Field(default_factory=list, description="Local paths or URLs to the product images")
    material_composition: str = Field(..., description="E.g., '100% Cotton', 'Mesh & Leather'")
    care_instructions: Optional[str] = Field(default=None, description="E.g., 'Hand wash cold', 'Machine wash warm'")
    visual_description: Optional[str] = Field(
        default=None, 
        description="A rich, verbose paragraph generated by the VLM detailing the visual appearance for semantic search."
    )
